--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/foobar/pics/walls/tiled3.png"

-- Special
background="#171a1d"
foreground="#c5c5c6"
cursor="#c5c5c6"

-- Colors
color0="#171a1d"
color1="#788696"
color2="#788696"
color3="#788696"
color4="#788696"
color5="#788696"
color6="#788696"
color7="#c5c5c6"
color8="#515355"
color9="#788696"
color10="#788696"
color11="#788696"
color12="#788696"
color13="#788696"
color14="#788696"
color15="#c5c5c6"
