# Shell variables
# Generated by 'wal'
wallpaper='/home/foobar/pics/walls/tiled3.png'

# Special
background='#171a1d'
foreground='#c5c5c6'
cursor='#c5c5c6'

# Colors
color0='#171a1d'
color1='#788696'
color2='#788696'
color3='#788696'
color4='#788696'
color5='#788696'
color6='#788696'
color7='#c5c5c6'
color8='#515355'
color9='#788696'
color10='#788696'
color11='#788696'
color12='#788696'
color13='#788696'
color14='#788696'
color15='#c5c5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
