set $bg_norm    #171a1d
set $border_norm #171a1d
set $fg_norm    #c5c5c6
set $bg_sel     #171a1d
set $border_sel #788696
set $fg_sel     #c5c5c6

client.focused          $border_sel $bg_sel $fg_sel   $border_sel $border_sel
client.focused_inactive $border_norm $bg_norm $fg_norm $border_norm $border_norm
client.unfocused        $border_norm $bg_norm $fg_norm $border_norm $border_norm
client.urgent           #788696 #788696 #c5c5c6 #788696 #788696
