set $bg_norm    {background}
set $border_norm {color0}
set $fg_norm    {foreground}
set $bg_sel     {color0}
set $border_sel {color9}
set $fg_sel     {foreground}

client.focused          $border_sel $bg_sel $fg_sel   $border_sel $border_sel
client.focused_inactive $border_norm $bg_norm $fg_norm $border_norm $border_norm
client.unfocused        $border_norm $bg_norm $fg_norm $border_norm $border_norm
client.urgent           {color1} {color1} {foreground} {color1} {color1}
